website:
  sidebar:
  - contents:
    - reference/index.qmd
    - contents:
      - reference/has_shape.qmd
      - reference/has_columns.qmd
      - reference/has_dtypes.qmd
      - reference/has_no_nulls.qmd
      - reference/has_no_infs.qmd
      - reference/unique.qmd
      - reference/unique_combination_of_columns.qmd
      - reference/not_constant.qmd
      - reference/accepted_values.qmd
      - reference/not_accepted_values.qmd
      - reference/has_mandatory_values.qmd
      - reference/not_null_proportion.qmd
      - reference/at_least_one.qmd
      - reference/accepted_range.qmd
      - reference/maintains_relationships.qmd
      - reference/is_monotonic.qmd
      - reference/custom_check.qmd
      - reference/mutually_exclusive_ranges.qmd
      - reference/column_is_within_n_std.qmd
      section: Check functions
    - contents:
      - reference/PolarsAssertError.qmd
      - reference/PolarsColumnType.qmd
      - reference/PolarsColumnBounds.qmd
      - reference/PolarsOverClauseInput.qmd
      section: Types and Exceptions
    id: reference
  - id: dummy-sidebar
