project:
  title: Pelage
  type: website
  output-dir: .


format:
  html:
    page-layout: full
    theme: zephyr
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "Pelage: Defensive analysis for Polars"
  description: "Pelage documentation website"
  page-navigation: true
  navbar:
    pinned: true
    left:
      - text: Get started
        file: notebooks/initial_readme.html
      - text: API Reference
        file: reference/index.html
    right:
      - icon: git
        href: https://github.com/alixtc/pelage/
        text: Git


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: pelage
  title: API Reference

  # write sidebar data to this file
  sidebar: _sidebar.yml
  sections:
    - title: Check functions
      desc: Functions to inspect docstrings.
      package: pelage.checks
      contents:
      - has_shape
      - has_columns
      - has_dtypes
      - has_no_nulls
      - has_no_infs
      - unique
      - unique_combination_of_columns
      - not_constant
      - accepted_values
      - not_accepted_values
      - has_mandatory_values
      - not_null_proportion
      - at_least_one
      - accepted_range
      - maintains_relationships
      - is_monotonic
      - custom_check
      - mutually_exclusive_ranges
      - column_is_within_n_std
    - title: Exceptions
      desc: Types aliases and custom exceptions
      package: pelage.checks
      contents:
        - PolarsAssertError
