on:
  workflow_dispatch:
  push:
    branches: [master]

name: Quarto Publish

jobs:
  tox-test:
    name: Version Tests with Tox
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python 3.8"
        uses: actions/setup-python@v5
        with:
          python-version-file: "3.8"
      - name: "Set up Python 3.9"
        uses: actions/setup-python@v5
        with:
          python-version-file: "3.9"
      - name: "Set up Python 3.10"
        uses: actions/setup-python@v5
        with:
          python-version-file: "3.10"
      - name: "Set up Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version-file: "3.11"
      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version-file: "3.12"
      - name: "Set up Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version-file: "3.13"

      - name: Install the project
        run: uv sync --dev
      - name: Install the project
        run: uv sync --dev
      - run: make tox


  quarto-publish-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
